### ISSUE TITLE
Requirements are out of date.

### ISSUE THREAD

**Issue by shawnohare** [nkrishnaswami/uscensus#2]
A `pip install uscensus` does not pull in dependencies. In particular, at least `sqlalchemy` and `fiona` are not fetched.

**Comment by nkrishnaswami** [comment]
Thanks, @shawnohare; I'll fix those up in the next day or so.

**Comment by nkrishnaswami** [comment]
I've updated the requirements.txt and uploaded a fresh version to pypi.

**Comment by nkrishnaswami** [comment]
Ah, I'd been updating requirements.txt rather than the list in setup.py. Should be fixed for real now. :)

**Comment by nkrishnaswami** [comment]
Should be up to date now. I'll make one more refactoring and reupload to pypi
